import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const layoutTs = readFileSync('src/app/layout/app-layout/app-layout.component.ts', 'utf8');
const layoutHtml = readFileSync('src/app/layout/app-layout/app-layout.component.html', 'utf8');
const componentTs = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.ts', 'utf8');
const componentHtml = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.html', 'utf8');
const componentScss = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.scss', 'utf8');
const serviceTs = readFileSync('src/app/core/services/floating-ai-assistant.service.ts', 'utf8');
const nginx = readFileSync('nginx.conf', 'utf8');
const packageJson = readFileSync('package.json', 'utf8');
const globalStyles = readFileSync('src/styles.scss', 'utf8');

assert.match(layoutTs, /FloatingAiAssistantComponent/, 'App layout should import the floating AI assistant component.');
assert.match(layoutHtml, /<app-floating-ai-assistant\s*\/>/, 'App layout should render the AI assistant beside floating chat.');
assert.match(componentTs, /allowedRoles\s*=\s*\[\s*'ADMIN',\s*'REGISTRAR',\s*'FINANCE',\s*'PRINCIPAL',\s*'TEACHER'\s*\]/, 'AI assistant should be gated to staff roles only.');
assert.match(componentTs, /currentUser\$|getUserRole\(\)/, 'AI assistant should read the current authenticated role.');
assert.match(componentTs, /Escape/, 'AI assistant should close from the Escape key.');
assert.match(componentHtml, /ai-assistant-launcher/, 'AI assistant should expose a separate floating launcher.');
assert.match(componentHtml, /AI Assistant/, 'AI assistant UI should be clearly labeled.');
assert.match(componentHtml, /<header class="ai-assistant-header">[\s\S]*<nav class="ai-workspace-tabs"/, 'Workspace tabs should live inside the compact header to avoid wasting vertical space.');
assert.doesNotMatch(componentHtml, /ai-category-tabs/, 'AI assistant should not show prompt category tabs in the history rail.');
assert.doesNotMatch(componentHtml, /ai-prompt-list/, 'AI assistant should not show preset prompt cards in the history rail.');
assert.match(componentHtml, /\*ngFor="let message of assistant\.messages\(\)[^"]*"/, 'AI assistant should render chat messages from the service.');
assert.match(componentHtml, /#messageList/, 'AI chat message list should expose a scroll container reference.');
assert.match(componentHtml, /\(scroll\)="onMessageListScroll\(\)"/, 'AI chat message list should detect manual scrolling.');
assert.match(componentTs, /AfterViewChecked/, 'AI assistant should react after streamed message DOM updates.');
assert.match(componentTs, /scrollMessageListToBottom/, 'AI assistant should keep streamed AI responses scrolled into view.');
assert.match(componentTs, /scrollTop\s*=\s*container\.scrollHeight/, 'AI assistant should pin the chat viewport to the newest response content.');
assert.match(componentTs, /shouldFollowMessageStream/, 'AI assistant should only auto-follow streamed responses while the user is near the newest message.');
assert.match(componentTs, /isMessageListNearBottom/, 'AI assistant should pause auto-scroll when the user scrolls up.');
assert.match(componentScss, /position:\s*fixed[\s\S]*inset:\s*0/, 'Open AI assistant should use a full-screen overlay.');
assert.match(componentScss, /grid-template-rows:\s*auto minmax\(0,\s*1fr\)/, 'AI overlay should use one compact chrome row and one content row.');
assert.match(componentScss, /padding:\s*0\.45rem 1rem/, 'AI header should use compact padding so Phoenix and Quipper have more vertical space.');
assert.match(componentHtml, /<div class="ai-resource-title">[\s\S]*Learning Resources[\s\S]*<strong>Quipper<\/strong>/, 'Quipper resource header should render as a compact single-line title.');
assert.doesNotMatch(componentHtml, /<p>Learning Resources<\/p>\s*<h3>Quipper<\/h3>/, 'Quipper resource header should not use stacked two-line title text.');
assert.match(componentScss, /grid-template-columns:\s*minmax\(0,\s*1fr\) auto/, 'Resource toolbar should keep title and action on one line.');
assert.match(componentScss, /min-height:\s*2\.65rem/, 'Resource toolbar should be short enough to avoid wasting vertical reading space.');
assert.match(componentScss, /right:\s*7rem/, 'AI launcher should sit beside the existing chat launcher.');
assert.match(serviceTs, /\/ai\/chat/, 'AI assistant service should call the backend AI proxy.');
assert.match(serviceTs, /downloadResponsePdf/, 'AI assistant should keep the per-response PDF export behavior.');
assert.doesNotMatch(serviceTs, /sk-or-v1/, 'OpenRouter API keys must not be shipped in the Angular bundle.');
console.log('floating AI assistant source test passed');

assert.match(nginx, /proxy_set_header\s+Authorization\s+\$http_authorization/, 'Nginx should forward bearer tokens to the API proxy.');

assert.match(serviceTs, /fetch\(/, 'AI assistant should use fetch so responses can stream like the desktop app.');
assert.match(serviceTs, /localStorage/, 'AI assistant should persist chat history in browser localStorage.');
assert.match(serviceTs, /AiAssistantSession/, 'AI assistant should model chat sessions for history management.');
assert.match(serviceTs, /startNewChat/, 'AI assistant should support starting a fresh chat.');
assert.match(serviceTs, /openSession/, 'AI assistant should support opening previous chat sessions.');
assert.match(serviceTs, /renameSession/, 'AI assistant should support renaming chat sessions.');
assert.match(serviceTs, /deleteSession/, 'AI assistant should support deleting chat sessions.');
assert.match(serviceTs, /AbortController/, 'AI assistant should use AbortController to stop active responses.');
assert.match(serviceTs, /stopResponse/, 'AI assistant should expose a stop response action.');
assert.doesNotMatch(serviceTs, /optimizePrompt/, 'AI assistant should not expose prompt optimization.');
assert.match(serviceTs, /getReader\(\)/, 'AI assistant should read streaming response chunks incrementally.');
assert.match(serviceTs, /TextDecoder/, 'AI assistant should decode streamed response chunks.');
assert.match(serviceTs, /appendToLastAssistantMessage/, 'AI assistant should append streamed tokens into the visible assistant message.');
assert.match(serviceTs, /backendContent/, 'AI assistant should allow hidden exact tool commands while displaying a friendly clicked action label.');
assert.match(serviceTs, /sendToolCommand/, 'AI assistant should expose a clickable learner tool command helper.');
assert.match(serviceTs, /\/ai\/chat\/stream/, 'AI assistant should call the backend streaming AI endpoint.');
assert.match(componentHtml, /\[innerHTML\]="renderMarkdown\(message\.content\)"/, 'Assistant messages should render GitHub-Flavored Markdown HTML.');
assert.match(componentHtml, /\(click\)="handleMarkdownAction\(\$event\)"/, 'Assistant markdown should handle clickable tool chips from the backend.');
assert.match(componentHtml, /New Chat/, 'AI assistant should expose a New Chat control.');
assert.match(componentHtml, /History/, 'AI assistant should expose a chat history control.');
assert.match(componentHtml, /Stop/, 'AI assistant should expose a stop button while streaming.');
assert.doesNotMatch(componentHtml, /Optimize/, 'AI assistant should not show an Optimize button.');
assert.match(componentHtml, /ai-history-panel/, 'AI assistant should render a chat history panel.');
assert.match(componentHtml, /renameChat/, 'AI assistant should expose rename chat actions.');
assert.match(componentHtml, /deleteChat/, 'AI assistant should expose delete chat actions.');
assert.match(componentTs, /DomSanitizer/, 'Markdown rendering should sanitize generated assistant HTML through Angular.');
assert.doesNotMatch(componentTs, /optimizeDraftPrompt/, 'Component should not wire prompt optimization.');
assert.match(componentTs, /startNewChat/, 'Component should wire new chat into the assistant service.');
assert.match(componentTs, /renderMarkdown/, 'Component should expose a markdown renderer for streamed AI output.');
assert.match(packageJson, /"markdown-it"/, 'AI response renderer should use markdown-it for robust markdown parsing.');
assert.match(packageJson, /"katex"/, 'AI response renderer should use KaTeX for clear math formatting.');
assert.match(packageJson, /"mermaid"/, 'AI response renderer should use Mermaid for diagrams.');
assert.match(packageJson, /"dompurify"/, 'AI response renderer should sanitize rich HTML before displaying it.');
assert.match(globalStyles, /katex\/dist\/katex\.min\.css/, 'Global styles should load KaTeX CSS for readable math output.');
assert.match(componentTs, /MarkdownIt/, 'Component should initialize markdown-it instead of relying only on a hand-written parser.');
assert.match(componentTs, /katex\.renderToString/, 'Component should render math through KaTeX.');
assert.match(componentTs, /DOMPurify\.sanitize/, 'Component should sanitize rich markdown HTML with DOMPurify.');
assert.match(componentTs, /data-ai-tool/, 'Markdown sanitizer should preserve AI tool action attributes.');
assert.match(componentTs, /data-student-id/, 'Markdown sanitizer should preserve exact learner ids for deterministic lookup.');
assert.match(componentTs, /handleMarkdownAction/, 'Component should handle clicked learner suggestions.');
assert.match(componentTs, /closest\('\.ai-tool-chip/, 'Component should only act on explicit AI tool chips.');
assert.match(componentTs, /renderMermaidDiagrams/, 'Component should render Mermaid diagram blocks after DOM updates.');
assert.match(componentTs, /renderMarkdownTable/, 'Markdown renderer should support GFM-style tables.');
assert.match(componentTs, /<pre><code>/, 'Markdown renderer should support fenced code blocks.');
assert.match(componentTs, /renderYoutubePreview/, 'Markdown renderer should turn YouTube links into preview cards.');
assert.match(componentTs, /renderVisualPlaceholder/, 'Markdown renderer should render diagram and illustration suggestions as visual placeholders.');
assert.match(componentTs, /renderCallout/, 'Markdown renderer should render teacher-friendly tip, warning, example, activity, and assessment callouts.');
assert.match(componentTs, /isChecklistItem/, 'Markdown renderer should support task-list checklist bullets.');
assert.match(componentTs, /protectMathSegments/, 'Markdown renderer should protect math expressions before inline formatting.');
assert.match(componentTs, /ai-math-inline/, 'Markdown renderer should render inline math without breaking multiplication symbols.');
assert.match(componentTs, /ai-math-block/, 'Markdown renderer should render block math and worked solutions distinctly.');
assert.doesNotMatch(componentTs, /replace\(\s*\/\\\*\(\.\+\?\)\\\*\//, 'Markdown renderer should not treat plain single asterisks as italics because that breaks multiplication.');
assert.match(componentScss, /ai-markdown[\s\S]*table/, 'Markdown output should style tables.');
assert.match(componentScss, /ai-markdown[\s\S]*pre/, 'Markdown output should style code blocks.');
assert.match(componentScss, /ai-youtube-preview/, 'Markdown output should style embedded YouTube preview cards.');
assert.match(componentScss, /ai-visual-placeholder/, 'Markdown output should style visual illustration placeholders.');
assert.match(componentScss, /ai-visual-grid/, 'Visual placeholders should include a clear diagram canvas area.');
assert.match(componentScss, /ai-math-inline/, 'Math inline output should have dedicated readable styling.');
assert.match(componentScss, /ai-math-block/, 'Math block output should have dedicated readable styling.');
assert.match(componentScss, /ai-callout/, 'Markdown output should style colored callout blocks.');
assert.match(componentScss, /::ng-deep[\s\S]*ai-tool-chip/, 'Markdown output should style clickable learner suggestion chips.');
assert.match(componentTs, /isPipeTableRow/, 'Markdown renderer should detect table-like pipe rows even when the model omits the separator line.');
assert.match(componentTs, /isTableSeparator/, 'Markdown renderer should skip markdown separator rows only when they exist.');
assert.match(componentTs, /ai-markdown-table/, 'Rendered tables should include a stable class for visible table styling.');
assert.match(componentScss, /::ng-deep[\s\S]*ai-markdown-table/, 'Styles for innerHTML tables should pierce Angular emulated encapsulation.');
assert.match(componentScss, /border-spacing:\s*0/, 'Rendered markdown tables should visually read as real bordered tables.');
assert.match(serviceTs, /workspaceTabs/, 'AI assistant should expose workspace tabs.');
assert.match(serviceTs, /Quipper/, 'AI assistant should include Quipper integration.');
assert.match(serviceTs, /Phoenix/, 'AI assistant should include Phoenix integration.');
assert.match(serviceTs, /178\.105\.105\.92:8123/, 'Quipper and Phoenix should point to the VPS-hosted education viewer.');
assert.match(readFileSync('../sms-nestjs-backend/src/ai/ai.service.ts', 'utf8'), /visual placeholders[\s\S]*YouTube preview links[\s\S]*colored callouts/i, 'Backend system prompt should ask the model for rich teacher-ready response formatting.');
assert.match(readFileSync('../sms-nestjs-backend/src/ai/ai.service.ts', 'utf8'), /math solutions[\s\S]*one step per line[\s\S]*final answer/i, 'Backend system prompt should preserve clear step-by-step math solutions.');
assert.doesNotMatch(componentHtml, /\[src\]="resourceFrameUrl\(/, 'Resource iframe src should not call a method during change detection because it can reload/flicker.');
assert.match(componentTs, /resourceFrameUrls/, 'Resource iframe URLs should be sanitized once and cached for stable iframe rendering.');
assert.match(componentHtml, /\[src\]="resourceFrameUrls\['Quipper'\]"/, 'Quipper should use a stable cached iframe URL.');
assert.match(serviceTs, /phoenixApiBaseUrl\s*=\s*'http:\/\/178\.105\.105\.92:3018'/, 'Phoenix should use the API service, not the Quipper static viewer route.');
assert.match(componentTs, /loadPhoenixBooks/, 'Phoenix should load from the Phoenix API instead of embedding a dead iframe route.');
assert.match(componentHtml, /ai-phoenix-workspace/, 'Phoenix should render with a native Angular resource panel.');
assert.match(componentHtml, /getPhoenixThumbnailUrl/, 'Phoenix book cards should render first-page WebP thumbnails.');
assert.match(componentTs, /thumbnail\/\$\{encodeURIComponent\(page\)\}\.webp/, 'Phoenix thumbnails should request WebP thumbnail images.');
assert.match(componentTs, /phoenixZoom/, 'Phoenix reader should track zoom state.');
assert.match(componentTs, /phoenixReaderMode/, 'Phoenix reader should support single and flip view state.');
assert.match(componentTs, /phoenixTool/, 'Phoenix reader should track the active annotation tool.');
assert.match(componentHtml, /setPhoenixZoom/, 'Phoenix reader should expose zoom controls.');
assert.match(componentHtml, /setPhoenixReaderMode\('flip'\)/, 'Phoenix reader should expose flip view controls.');
assert.match(componentHtml, /ai-phoenix-annotation-tools/, 'Phoenix reader should expose annotation tools.');
assert.match(componentHtml, /phoenixVisiblePages\(\)/, 'Phoenix reader should render one or two visible pages depending on view mode.');
assert.match(globalStyles, /ai-phoenix-page-stage\.flip-view/, 'Phoenix flip view should use a two-page layout.');
assert.match(globalStyles, /ai-phoenix-annotation-layer/, 'Phoenix reader should render an annotation overlay layer.');
