import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const layoutTs = readFileSync('src/app/layout/app-layout/app-layout.component.ts', 'utf8');
const layoutHtml = readFileSync('src/app/layout/app-layout/app-layout.component.html', 'utf8');
const componentTs = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.ts', 'utf8');
const componentHtml = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.html', 'utf8');
const componentScss = readFileSync('src/app/shared/components/floating-ai-assistant/floating-ai-assistant.component.scss', 'utf8');
const serviceTs = readFileSync('src/app/core/services/floating-ai-assistant.service.ts', 'utf8');
const nginx = readFileSync('nginx.conf', 'utf8');
const packageJson = readFileSync('package.json', 'utf8');
const globalStyles = readFileSync('src/styles.scss', 'utf8');

assert.match(layoutTs, /FloatingAiAssistantComponent/, 'App layout should import the floating AI assistant component.');
assert.match(layoutHtml, /<app-floating-ai-assistant\s*\/>/, 'App layout should render the AI assistant beside floating chat.');
assert.match(componentTs, /allowedRoles\s*=\s*\[\s*'ADMIN',\s*'REGISTRAR',\s*'FINANCE',\s*'PRINCIPAL',\s*'TEACHER'\s*\]/, 'AI assistant should be gated to staff roles only.');
assert.match(componentTs, /currentUser\$|getUserRole\(\)/, 'AI assistant should read the current authenticated role.');
assert.match(componentTs, /Escape/, 'AI assistant should close from the Escape key.');
assert.match(componentHtml, /ai-assistant-launcher/, 'AI assistant should expose a separate floating launcher.');
assert.match(componentHtml, /AI Assistant/, 'AI assistant UI should be clearly labeled.');
assert.match(componentHtml, /<header class="ai-assistant-header">[\s\S]*<nav class="ai-workspace-tabs"/, 'Workspace tabs should live inside the compact header to avoid wasting vertical space.');
assert.doesNotMatch(componentHtml, /ai-category-tabs/, 'AI assistant should not show prompt category tabs in the history rail.');
assert.doesNotMatch(componentHtml, /ai-prompt-list/, 'AI assistant should not show preset prompt cards in the history rail.');
assert.match(componentHtml, /\*ngFor="let message of assistant\.messages\(\)[^"]*"/, 'AI assistant should render chat messages from the service.');
assert.match(componentHtml, /#messageList/, 'AI chat message list should expose a scroll container reference.');
assert.match(componentHtml, /\(scroll\)="onMessageListScroll\(\)"/, 'AI chat message list should detect manual scrolling.');
assert.match(componentTs, /AfterViewChecked/, 'AI assistant should react after streamed message DOM updates.');
assert.match(componentTs, /scrollMessageListToBottom/, 'AI assistant should keep streamed AI responses scrolled into view.');
assert.match(componentTs, /scrollTop\s*=\s*container\.scrollHeight/, 'AI assistant should pin the chat viewport to the newest response content.');
assert.match(componentTs, /shouldFollowMessageStream/, 'AI assistant should only auto-follow streamed responses while the user is near the newest message.');
assert.match(componentTs, /isMessageListNearBottom/, 'AI assistant should pause auto-scroll when the user scrolls up.');
assert.match(componentScss, /position:\s*fixed[\s\S]*inset:\s*0/, 'Open AI assistant should use a full-screen overlay.');
assert.match(componentScss, /grid-template-rows:\s*auto minmax\(0,\s*1fr\)/, 'AI overlay should use one compact chrome row and one content row.');
assert.match(componentScss, /padding:\s*0\.45rem 1rem/, 'AI header should use compact padding so Phoenix and Quipper have more vertical space.');
assert.match(componentHtml, /<div class="ai-resource-title">[\s\S]*Learning Resources[\s\S]*<strong>Quipper<\/strong>/, 'Quipper resource header should render as a compact single-line title.');
assert.doesNotMatch(componentHtml, /<p>Learning Resources<\/p>\s*<h3>Quipper<\/h3>/, 'Quipper resource header should not use stacked two-line title text.');
assert.match(componentScss, /grid-template-columns:\s*minmax\(0,\s*1fr\) auto/, 'Resource toolbar should keep title and action on one line.');
assert.match(componentScss, /min-height:\s*2\.65rem/, 'Resource toolbar should be short enough to avoid wasting vertical reading space.');
assert.match(componentScss, /right:\s*7rem/, 'AI launcher should sit beside the existing chat launcher.');
assert.match(serviceTs, /\/ai\/chat/, 'AI assistant service should call the backend AI proxy.');
assert.match(serviceTs, /downloadResponsePdf/, 'AI assistant should keep the per-response PDF export behavior.');
assert.doesNotMatch(serviceTs, /sk-or-v1/, 'OpenRouter API keys must not be shipped in the Angular bundle.');
console.log('floating AI assistant source test passed');

assert.match(nginx, /proxy_set_header\s+Authorization\s+\$http_authorization/, 'Nginx should forward bearer tokens to the API proxy.');

assert.match(serviceTs, /fetch\(/, 'AI assistant should use fetch so responses can stream like the desktop app.');
assert.match(serviceTs, /localStorage/, 'AI assistant should persist chat history in browser localStorage.');
assert.match(serviceTs, /AiAssistantSession/, 'AI assistant should model chat sessions for history management.');
assert.match(serviceTs, /startNewChat/, 'AI assistant should support starting a fresh chat.');
assert.match(serviceTs, /openSession/, 'AI assistant should support opening previous chat sessions.');
assert.match(serviceTs, /renameSession/, 'AI assistant should support renaming chat sessions.');
assert.match(serviceTs, /deleteSession/, 'AI assistant should support deleting chat sessions.');
assert.match(serviceTs, /AbortController/, 'AI assistant should use AbortController to stop active responses.');
assert.match(serviceTs, /stopResponse/, 'AI assistant should expose a stop response action.');
assert.doesNotMatch(serviceTs, /optimizePrompt/, 'AI assistant should not expose prompt optimization.');
assert.match(serviceTs, /getReader\(\)/, 'AI assistant should read streaming response chunks incrementally.');
assert.match(serviceTs, /TextDecoder/, 'AI assistant should decode streamed response chunks.');
assert.match(serviceTs, /appendToLastAssistantMessage/, 'AI assistant should append streamed tokens into the visible assistant message.');
assert.match(serviceTs, /maxHistoryMessages\s*=\s*6/, 'AI assistant should cap sent chat history to the newest 6 messages for faster model responses.');
assert.match(serviceTs, /maxHistoryContentLength\s*=\s*800/, 'AI assistant should cap oversized history message content before sending it to the backend.');
assert.match(serviceTs, /prepareMessageHistory/, 'AI assistant should prepare a bounded history payload instead of sending full saved sessions.');
assert.match(serviceTs, /truncateHistoryContent/, 'AI assistant should truncate large previous AI responses to avoid slow request bodies.');
assert.match(serviceTs, /\/ai\/chat\/stream/, 'AI assistant should call the backend streaming AI endpoint.');
assert.match(componentHtml, /\[innerHTML\]="renderMarkdown\(message\)"/, 'Assistant messages should render cached GitHub-Flavored Markdown HTML.');
assert.match(componentHtml, /New Chat/, 'AI assistant should expose a New Chat control.');
assert.match(componentHtml, /ai-mode-switch/, 'AI assistant should expose a Single/Dual mode switcher.');
assert.match(componentHtml, /Dual/, 'AI assistant should label the second response mode as Dual.');
assert.match(componentHtml, /ai-dual-response-grid/, 'Dual mode should render two response panes side by side on desktop.');
assert.match(componentTs, /chatViewMode/, 'Component should track whether the assistant is in single or dual chat mode.');
assert.match(componentTs, /setChatViewMode/, 'Component should expose a mode switch handler.');
assert.match(serviceTs, /sendDualMessage/, 'AI assistant service should send one prompt to two model slots in dual mode.');
assert.match(serviceTs, /modelSlot:\s*'default'/, 'Dual mode should request the default OpenRouter model slot.');
assert.match(serviceTs, /modelSlot:\s*'comparison'/, 'Dual mode should request the comparison OpenRouter model slot.');
assert.match(serviceTs, /dualGroupId/, 'Dual response messages should be grouped as one user turn.');
assert.match(componentHtml, /History/, 'AI assistant should expose a chat history control.');
assert.match(componentHtml, /Stop/, 'AI assistant should expose a stop button while streaming.');
assert.match(componentHtml, /ai-thinking-card/, 'AI assistant should show a structured pending response bubble while waiting.');
assert.match(componentHtml, /Preparing your answer/, 'AI pending preview should use clear waiting copy.');
assert.match(componentHtml, /ai-response-actions/, 'AI assistant should show per-response action buttons.');
assert.match(componentHtml, /copyResponse\(message\)/, 'AI assistant should expose a Copy action for each response.');
assert.match(componentHtml, /copyResponseMarkdown\(message\)/, 'AI assistant should expose a Copy as Markdown action for each response.');
assert.match(componentHtml, /regenerateLastResponse/, 'AI assistant should expose a Regenerate action.');
assert.match(componentHtml, /continueLastResponse/, 'AI assistant should expose a Continue action.');
assert.match(componentHtml, /ai-followup-chips/, 'AI assistant should render quick follow-up chips below responses.');
assert.match(componentHtml, /ai-stream-cursor/, 'AI assistant should show a streaming cursor while generating.');
assert.doesNotMatch(componentHtml, /class="ai-loading"/, 'AI assistant should replace the old loose dot loader with the pending response bubble.');
assert.match(componentTs, /copyText/, 'AI assistant component should support copying response text.');
assert.match(componentTs, /sendFollowUp/, 'AI assistant component should send quick follow-up prompts.');
assert.match(serviceTs, /regenerateLastResponse/, 'AI assistant service should support regenerating from the last user prompt.');
assert.match(serviceTs, /continueLastResponse/, 'AI assistant service should support continuing the prior response.');
assert.match(globalStyles, /ai-thinking-card/, 'AI assistant should style the pending response bubble globally to stay under component budgets.');
assert.match(globalStyles, /ai-thinking-skeleton/, 'AI assistant should show skeleton shimmer lines while waiting.');
assert.match(globalStyles, /ai-followup-chips/, 'AI assistant should style quick follow-up chips.');
assert.match(globalStyles, /prefers-reduced-motion/, 'AI assistant should respect reduced-motion settings.');
assert.doesNotMatch(componentHtml, /Optimize/, 'AI assistant should not show an Optimize button.');
assert.match(componentHtml, /ai-history-panel/, 'AI assistant should render a chat history panel.');
assert.match(componentHtml, /renameChat/, 'AI assistant should expose rename chat actions.');
assert.match(componentHtml, /deleteChat/, 'AI assistant should expose delete chat actions.');
assert.match(componentTs, /DomSanitizer/, 'Markdown rendering should sanitize generated assistant HTML through Angular.');
assert.doesNotMatch(componentTs, /optimizeDraftPrompt/, 'Component should not wire prompt optimization.');
assert.match(componentTs, /startNewChat/, 'Component should wire new chat into the assistant service.');
assert.match(componentTs, /renderMarkdown/, 'Component should expose a markdown renderer for streamed AI output.');
assert.match(packageJson, /"markdown-it"/, 'AI response renderer should use markdown-it for robust markdown parsing.');
assert.match(packageJson, /"katex"/, 'AI response renderer should use KaTeX for clear math formatting.');
assert.match(packageJson, /"mermaid"/, 'AI response renderer should use Mermaid for diagrams.');
assert.match(packageJson, /"dompurify"/, 'AI response renderer should sanitize rich HTML before displaying it.');
assert.match(globalStyles, /katex\/dist\/katex\.min\.css/, 'Global styles should load KaTeX CSS for readable math output.');
assert.match(componentTs, /MarkdownIt/, 'Component should initialize markdown-it instead of relying only on a hand-written parser.');
assert.match(componentTs, /katex\.renderToString/, 'Component should render math through KaTeX.');
assert.match(componentTs, /DOMPurify\.sanitize/, 'Component should sanitize rich markdown HTML with DOMPurify.');
assert.match(componentTs, /renderMermaidDiagrams/, 'Component should render Mermaid diagram blocks after DOM updates.');
assert.match(componentTs, /renderMarkdownTable/, 'Markdown renderer should support GFM-style tables.');
assert.match(componentTs, /<pre><code>/, 'Markdown renderer should support fenced code blocks.');
assert.match(componentTs, /renderYoutubePreview/, 'Markdown renderer should turn YouTube links into preview cards.');
assert.match(componentTs, /renderVisualPlaceholder/, 'Markdown renderer should render diagram and illustration suggestions as visual placeholders.');
assert.match(componentTs, /renderCallout/, 'Markdown renderer should render teacher-friendly tip, warning, example, activity, and assessment callouts.');
assert.match(componentTs, /isChecklistItem/, 'Markdown renderer should support task-list checklist bullets.');
assert.match(componentTs, /protectMathSegments/, 'Markdown renderer should protect math expressions before inline formatting.');
assert.match(componentTs, /ai-math-inline/, 'Markdown renderer should render inline math without breaking multiplication symbols.');
assert.match(componentTs, /ai-math-block/, 'Markdown renderer should render block math and worked solutions distinctly.');
assert.doesNotMatch(componentTs, /replace\(\s*\/\\\*\(\.\+\?\)\\\*\//, 'Markdown renderer should not treat plain single asterisks as italics because that breaks multiplication.');
assert.match(componentScss, /ai-markdown[\s\S]*table/, 'Markdown output should style tables.');
assert.match(componentTs, /data-ai-tool/, 'AI assistant should preserve clickable AI tool actions emitted by backend learner search.');
assert.match(componentTs, /rawTarget instanceof Element/, 'AI tool clicks should work when the browser targets nested text or elements inside a rendered markdown button.');
assert.match(componentTs, /closest\('\[data-ai-tool\]\[data-student-id\]'\)/, 'AI tool clicks should delegate from rendered markdown to data-ai-tool buttons.');
assert.match(componentTs, /getAttribute\('data-ai-tool'\)/, 'AI tool clicks should read rendered DOM attributes instead of relying on Angular bindings inside innerHTML.');
assert.match(componentTs, /stopPropagation\(\)/, 'AI tool clicks should not bubble into surrounding markdown behavior.');
assert.match(componentTs, /onMessageListWheel/, 'AI chat message list should own mouse-wheel scrolling inside the overlay.');
assert.match(componentHtml, /\(wheel\)="onMessageListWheel\(\$event\)"/, 'AI message list should wire wheel events to the scroll handler.');
assert.doesNotMatch(componentHtml, /\(pointerup\)="handleMarkdownAction\(\$event\)"/, 'AI markdown should not execute actions from pointer release because it interferes with response text selection.');
assert.match(componentTs, /lastToolActionKey/, 'AI tool actions should guard against duplicate action execution.');
assert.match(componentScss, /overscroll-behavior:\s*contain/, 'AI chat scrolling should not leak wheel movement to the page behind the overlay.');
assert.match(componentScss, /user-select:\s*text/, 'AI response text should be selectable for copy operations.');
assert.match(componentTs, /renderedMarkdownCache/, 'AI response markdown should be cached so change detection does not replace selectable text while dragging.');
assert.match(componentTs, /getCachedRenderedMarkdown/, 'AI response rendering should return stable SafeHtml for unchanged message content.');
assert.doesNotMatch(componentHtml, /\(pointerup\)=\"handleMarkdownAction\(\$event\)\"/, 'AI markdown should not execute actions from pointerup because it interferes with text selection.');
assert.match(serviceTs, /window\.open\('',\s*'_blank'\)/, 'AI response PDF export should open a writable blank window.');
assert.doesNotMatch(serviceTs, /window\.open\('',\s*'_blank',\s*'noopener,noreferrer'\)/, 'AI response PDF export must not use noopener because it can return a null window handle.');
assert.match(componentScss, /touch-action:\s*manipulation/, 'AI tool buttons should respond reliably to pointer interaction.');
assert.match(componentTs, /data-ai-prompt/, 'AI suggestion actions should preserve executable prompt text through markdown sanitization.');
assert.match(componentTs, /renderSuggestionAction/, 'AI suggestion lines should be rendered as executable highlighted actions.');
assert.match(componentTs, /executePromptAction/, 'AI suggestion actions should send a new AI prompt when clicked.');
assert.match(componentTs, /hasActiveTextSelection/, 'AI suggestion actions should not execute while the user is selecting response text.');
assert.match(componentTs, /role="button"/, 'AI suggestion actions should render as selection-friendly role buttons instead of native buttons.');
assert.match(componentScss, /ai-suggestion-action/, 'AI suggestion actions should be visibly highlighted.');
assert.match(componentScss, /ai-markdown[\s\S]*pre/, 'Markdown output should style code blocks.');
assert.match(componentScss, /ai-youtube-preview/, 'Markdown output should style embedded YouTube preview cards.');
assert.match(componentScss, /ai-visual-placeholder/, 'Markdown output should style visual illustration placeholders.');
assert.match(componentScss, /ai-visual-grid/, 'Visual placeholders should include a clear diagram canvas area.');
assert.match(componentScss, /ai-math-inline/, 'Math inline output should have dedicated readable styling.');
assert.match(componentScss, /ai-math-block/, 'Math block output should have dedicated readable styling.');
assert.match(componentScss, /ai-callout/, 'Markdown output should style colored callout blocks.');
assert.match(componentTs, /isPipeTableRow/, 'Markdown renderer should detect table-like pipe rows even when the model omits the separator line.');
assert.match(componentTs, /isTableSeparator/, 'Markdown renderer should skip markdown separator rows only when they exist.');
assert.match(componentTs, /ai-markdown-table/, 'Rendered tables should include a stable class for visible table styling.');
assert.match(componentScss, /::ng-deep[\s\S]*ai-markdown-table/, 'Styles for innerHTML tables should pierce Angular emulated encapsulation.');
assert.match(componentScss, /border-spacing:\s*0/, 'Rendered markdown tables should visually read as real bordered tables.');
assert.match(serviceTs, /workspaceTabs/, 'AI assistant should expose workspace tabs.');
assert.match(serviceTs, /Quipper/, 'AI assistant should include Quipper integration.');
assert.match(serviceTs, /Phoenix/, 'AI assistant should include Phoenix integration.');
assert.match(serviceTs, /Image Generation/, 'AI assistant should include an Image Generation workspace tab.');
assert.match(serviceTs, /\/ai\/image/, 'Image Generation should call the backend image proxy.');
assert.match(serviceTs, /generateImage/, 'AI assistant service should expose image generation.');
assert.match(componentHtml, /ai-image-workspace/, 'Image Generation should render a native Angular workspace.');
assert.match(componentHtml, /Generate Image/, 'Image Generation workspace should expose a clear generate button.');
assert.match(componentHtml, /generatedImages/, 'Image Generation workspace should render generated image results.');
assert.match(componentTs, /imagePrompt/, 'Image Generation should track the prompt input.');
assert.match(componentTs, /generateImage/, 'Component should wire image generation into the assistant service.');
assert.match(componentScss, /ai-image-workspace/, 'Image Generation workspace should have dedicated layout styles.');
assert.match(serviceTs, /Quipper:\s*'\/quipper\/'/, 'Quipper should use a relative proxy URL to avoid mixed content.');
assert.match(readFileSync('../sms-nestjs-backend/src/ai/ai.service.ts', 'utf8'), /visual placeholders[\s\S]*YouTube preview links[\s\S]*colored callouts/i, 'Backend system prompt should ask the model for rich teacher-ready response formatting.');
assert.match(readFileSync('../sms-nestjs-backend/src/ai/ai.service.ts', 'utf8'), /math solutions[\s\S]*one step per line[\s\S]*final answer/i, 'Backend system prompt should preserve clear step-by-step math solutions.');
assert.doesNotMatch(componentHtml, /\[src\]="resourceFrameUrl\(/, 'Resource iframe src should not call a method during change detection because it can reload/flicker.');
assert.match(componentTs, /resourceFrameUrls/, 'Resource iframe URLs should be sanitized once and cached for stable iframe rendering.');
assert.match(componentHtml, /\[src\]="resourceFrameUrls\['Quipper'\]"/, 'Quipper should use a stable cached iframe URL.');
assert.match(serviceTs, /phoenixApiBaseUrl\s*=\s*''/, 'Phoenix should use a relative proxy API URL to avoid mixed content.');
assert.match(componentTs, /loadPhoenixBooks/, 'Phoenix should load from the Phoenix API instead of embedding a dead iframe route.');
assert.match(componentHtml, /ai-phoenix-workspace/, 'Phoenix should render with a native Angular resource panel.');
assert.match(componentHtml, /getPhoenixThumbnailUrl/, 'Phoenix book cards should render first-page WebP thumbnails.');
assert.match(componentTs, /thumbnail\/\$\{encodeURIComponent\(page\)\}\.webp/, 'Phoenix thumbnails should request WebP thumbnail images.');
assert.match(componentTs, /phoenixZoom/, 'Phoenix reader should track zoom state.');
assert.match(componentTs, /phoenixReaderMode/, 'Phoenix reader should support single and flip view state.');
assert.match(componentTs, /phoenixTool/, 'Phoenix reader should track the active annotation tool.');
assert.match(componentHtml, /setPhoenixZoom/, 'Phoenix reader should expose zoom controls.');
assert.match(componentHtml, /setPhoenixReaderMode\('flip'\)/, 'Phoenix reader should expose flip view controls.');
assert.match(componentHtml, /ai-phoenix-annotation-tools/, 'Phoenix reader should expose annotation tools.');
assert.match(componentHtml, /phoenixVisiblePages\(\)/, 'Phoenix reader should render one or two visible pages depending on view mode.');
assert.match(globalStyles, /ai-phoenix-page-stage\.flip-view/, 'Phoenix flip view should use a two-page layout.');
assert.match(globalStyles, /ai-phoenix-annotation-layer/, 'Phoenix reader should render an annotation overlay layer.');


